import { Component, OnInit, AfterContentInit } from '@angular/core';
import { Note, StaffType } from 'src/app/shared/instrument-variables';
import { ContextService } from 'src/app/shared/context.service';

@Component({
  selector: 'app-staff',
  templateUrl: './staff.component.html',
  styleUrls: ['./staff.component.css']
})
export class StaffComponent implements OnInit, AfterContentInit {

  constructor(private context:ContextService) { }

  ngOnInit(): void {
  }

  /**
   * After the document construction, the notes should be all hidden and only shown when a new note 
   * is generated by the game manager.
   */
  ngAfterContentInit(): void {

    // Hiding unwanted staff part
    switch (this.context.getInstrument().staffType){
      case StaffType.HIGH :
        let staffLow = document.getElementById("low");
        if (staffLow != null) {
          staffLow.style.display = "none";
        }
      break;
      case StaffType.LOW :
        let staffHigh = document.getElementById("high");
        if (staffHigh != null) {
          staffHigh.style.display = "none";
        }
        break;
      default:
        break;
    }

    // We must link each svg note to the corresponding click event.
    for (const note in Note) {
      // Initialy hiding the notes, waiting for the game manager to tell which note should be seen.
      if (Note.hasOwnProperty(note)) {
        let obj = document.getElementById(Note[note].toString());
        if (obj != null) {
          obj.style.display = "none";
        }
      }
    }
  }


}
