import { AfterContentInit, Component, OnInit } from '@angular/core';
import { ContextService } from 'src/app/shared/context.service';
import { AllNotes, StaffType, Note } from 'src/app/shared/instrument-variables';
import { GameManagerService } from 'src/app/shared/game-manager.service';

@Component({
  selector: 'app-staff',
  templateUrl: './staff.component.html',
  styleUrls: ['./staff.component.css']
})
export class StaffComponent implements OnInit, AfterContentInit {

  constructor(private context: ContextService, private game: GameManagerService) {
    // Subscribing to different game events
    this.cleanAllNotes();

    // region on new note
    this.game.eventNewNote.subscribe(
      (emittedNote: Note) => {
        // New note generated
        console.log("Asked for");
        console.log(emittedNote);
        for (let note of AllNotes.notes) {
          let doc: HTMLElement = document.getElementById(note.name);
          if (doc != null && (emittedNote.name == note.name)) {
            doc.style.visibility = "visible"
            console.log("Found note");
          } else if (doc != null && (emittedNote.name != note.name)) {
            doc.style.visibility = "hidden";
          }
        }
      }
    );
    // endregion on new note

    // region on note check
    this.game.eventNoteCheck.subscribe((success:boolean)=>{
      //TODO: add some animation on failures
      if (success){
        this.game.askNewNote(this.context.getInstrument());
      } else {

      }

    });
    // endregion on note check

  }


  ngOnInit(): void {
  }

  /**
   * After the document construction, the notes should be all hidden and only shown when a new note 
   * is generated by the game manager.
   */
  ngAfterContentInit(): void {

    // Hiding unwanted staff part
    switch (this.context.getInstrument().staffType) {
      case StaffType.HIGH:
        let staffLow = document.getElementById("low");
        if (staffLow != null) {
          staffLow.style.visibility = "hidden";
        }
        break;
      case StaffType.LOW:
        let staffHigh = document.getElementById("high");
        if (staffHigh != null) {
          staffHigh.style.visibility = "hidden";
        }
        break;
      default:
        break;
    }

    // We must link each svg note to the corresponding click event.

  }

  private cleanAllNotes(): void {
    for (const note of AllNotes.notes) {
      let obj = document.getElementById(note.name);
      if (obj != null) {
        obj.style.visibility = "hidden";
      }
    }
  }

}



